manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: te9no
      url-base: https://github.com/te9no
    - name: zettaface
      url-base: https://github.com/zettaface
    - name: kot149
      url-base: https://github.com/kot149
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
  projects:
    - name: zmk
      #remote: zmkfirmware
      remote: te9no
      revision: main
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    - name: zmk-analog-input-driver
      remote: badjeff
      revision: main
    # - name: zmk-dongle-display
    #   remote: te9no
    #   revision: main
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
    - name: zmk-driver-LIS3MDLTR
      remote: te9no
      revision: main
    - name: zmk-layout-shift
      remote: kot149
      revision: v1
    - name: zmk-input-processor-keybind
      remote: te9no
      revision: main
    # - name: zmk-leader-key
    #   remote: urob
    #   revision: v0.2.1 # set to same as ZMK version above
  self:
    path: config
    